### ISSUE TITLE
Cached profile Not updated when updating a device

### ISSUE THREAD

**Issue by novuscy** [edgexfoundry/device-sdk-go#513]
Due to the limitation that you can't update a profile when it is still in use by a device, my approach to update a profile of a device is:
`create a new profile -> update the device with the new profile -> delete the old profile`

but when I tested this approach, this error showed up:
`msg="internal error; Device: somedevice searching somecommand in cache failed; GET"`

after restarting the Device Service, the error disappeared and everything works fine, perhaps the cached profile in the Device Service is not updated? When using DeviceProfiles() function to retrieve the cached profiles, I see that cached profiles are still the old ones, but profiles from Core-Metadata API call are new ones, is there a function to force the Device Service purge the cache and to get profiles from metadata?

**Comment by novuscy** [comment]
After some testing, I can confirm that the profiles in the cached devices are updated, but the cached profiles are NOT, I tried to call the UpdateDeviceProfile(), but got error:
` msg="DeviceProfile 387ac610-8b11-4609-bfa0-5567cf857ca6 cannot be found in cache"`

I tried to call the AddDeviceProfile(), got error:
`"Add Profile failed profile|rs232-1@1587787543787, error: 409 - Duplicate profile name profile|rs232-1@1587787543787\n"`

**Comment by cloudxxx8** [comment]
@novuscy we noticed this issue and fixed in https://github.com/edgexfoundry/device-sdk-go/pull/486
could you please try again with the latest master branch?  thanks.

**Comment by novuscy** [comment]
> @novuscy we noticed this issue and fixed in #486
> could you please try again with the latest master branch? thanks.

I tested with the master branch v1.2.0-dev.34, still the same error. I thought that #486 was to update the cache when adding new device, but I was just updating the device using PUT method.

I did some digging around the code in internal/handler/callback/device.go, the profile update only occurred in the method == http.MethodPost condition, but not handled in the method == http.MethodPut.

**Comment by cloudxxx8** [comment]
We made for POST only because the current core-metadata doesn’t allow profile update unless removing and recreating all devices.
How could you update profile and device at the same time?

**Comment by novuscy** [comment]
I did not update the profile, I only updated the device with a new profile. I don't think the new profile has been added to cache through this operation.

**Comment by cloudxxx8** [comment]
I got it, and we could fix it

**Comment by hahattan** [comment]
@novuscy could please help verify PR #514 resolved this issue?

**Comment by novuscy** [comment]
The PR works, thanks a lot!
