### ISSUE TITLE
bug(v2): service.DeviceProfiles() incorrect result

### ISSUE THREAD

**Issue by AlexCuse** [edgexfoundry/device-sdk-go#871]
I have a device service with 3 registered profiles, and I am trying to range over .DeviceProfiles() to retrieve metadata needed for an in process event.  If I log the profile I notice it goes through the loop three times but each time inspects the same profile.  Eg:

```
for i, p := range service.RunningService().DeviceProfiles() {
    lc.Debugf("%d: %+v", i, p) //verify index updates as p remains the same
}
```

I am loading profiles from files on disk and in this case they are NOT being updated.  Using latest master for sdk and core services.    Should have be able to look closer next week.

**Comment by cloudxxx8** [comment]
@AlexCuse Do you also create devices with these profiles?  There is no direct connection between Device Profile and Device Service, so the Device Profile won't be added into cache if there is no associated Device instance.

**Comment by AlexCuse** [comment]
@cloudxxx8 yes there are devices associated, all loaded from disk originally.  When I try going from the device using `service.GetProfileByName` I get the same profile back for each distinct name as well.

**Comment by cloudxxx8** [comment]
@AlexCuse this issue should be resolved now.  please help verify it.  thanks for reporting this bug.

**Comment by AlexCuse** [comment]
@cloudxxx8 I looked at the fix and it makes sense - but I am still seeing the incorrect profiles, at least when using `GetProfileByName`.

Is there any effort made to persist the cache that I need to work around, or is it rebuilt from metadata on each launch making  docker down/up sufficient?  The service I am working with right now only has two profiles loaded (verified through `/api/v2/deviceprofile/all`) but I am getting one of them back from the cache each time.  It is the one that appears last in the list returned by 'all' if that helps.

**Comment by AlexCuse** [comment]
I messed something up at first but this looks right thanks!
